/** Shape of src/data/wencheng.json (generated by scripts/build-data.ts). */

export type Source = "daxue" | "wencheng" | "wenzhou";

export const SOURCE_PRIORITY: readonly Source[] = ["daxue", "wencheng", "wenzhou"];

export interface Reading {
  /** IPA with trailing tone digit, e.g. "ȵi4" */
  ipa: string;
  /** 0 = neutral tone, 1–8 = the eight Wu tone categories */
  tone: number;
  gloss?: string;
}

export interface SourceReadings {
  source: Source;
  readings: Reading[];
}

export interface CharEntry extends SourceReadings {
  /** Readings from lower-priority sources, in priority order */
  alt?: SourceReadings[];
}

export interface WenchengData {
  meta: { generated: string; repo: string; commit: string; files: Record<Source, string> };
  chars: Record<string, CharEntry>;
}
